export const ActionTypes = {
  ADD_SHOPE: "ADD_SHOPE",
  DELETE_SHOPE: "DELETE_SHOPE",
  FILTER_BY_AREA:"FILTER_BY_AREA",
  FILTER_BY_CATEGORY:"FILTER_BY_CATEGORY",
  FILTER_BY_STATUS:"FILTER_BY_CATEGORY",
  ADD_TO_FILTER: "ADD_TO_FILTER"
};
 